name: minify
on: 
  push:
    branches:
      - main

jobs:
  # Minify js
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Setup node
        uses: actions/setup-node@v3
      - name: Install terser
        run: npm install -g terser
      - name: Run terser vpde-sliders.js
        run: terser --compress --mangle --module --output vpde-sliders.min.js -- vpde-sliders.js
      - name: Commit vpde-sliders.min.js
        uses: EndBug/add-and-commit@v9
        with:
          add: vpde-sliders.min.js
          message: "Minify vpde-sliders.min.js"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2