name: minify
on: 
  push:
    branches:
      - main

jobs:
  # Minify js
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Setup node
        uses: actions/setup-node@v3
      - name: Install terser
        run: npm install -g terser
      - name: Run terser vpde-sliders.js
        run: terser --compress --mangle --module --output vpde-sliders.min.js -- vpde-sliders.js
      - name: Commit vpde-sliders.min.js
        uses: EndBug/add-and-commit@v9
        with:
          add: vpde-sliders.min.js
          message: "Minify vpde-sliders.js"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        
# Deployment job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
